#!/usr/bin/python

# libparticlasm2 configuration header generator from make parameters
# takes a list of targets as arguments
# Copyright (C) 2012, Leszek Godlewski <github@inequation.org>

import sys, os

available_targets = [
    "RuntimeInterpreter",
    "X86Assembly"
]
requested_targets = []

print("Processing requested targets...")
for arg in sys.argv[1:]:
    if (arg not in available_targets):
        print("Requested target {0} is not supported!".format(arg))
        sys.exit(1)
    requested_targets.append(
        available_targets.pop(
            available_targets.index(arg)
        )
    )

print("Writing configuration header...")
outfile = open("Config.h", 'w')
outfile.write("/*\n")
outfile.write("Particlasm configuration header file\n")
outfile.write("AUTOGENERATED - DO NOT MODIFY!!!\n")
outfile.write("If you need to change something, change the make configuration and re-run make.\n")
outfile.write("Copyright (C) 2012, Leszek Godlewski <github@inequation.org>\n")
outfile.write("*/\n\n")
outfile.write("#ifndef CONFIG_H\n")
outfile.write("#define CONFIG_H\n\n")

for target in requested_targets:
    outfile.write("#define WITH_{0} 1\n".format(target.upper()))
for target in available_targets:
    outfile.write("#define WITH_{0} 0\n".format(target.upper()))

outfile.write("\n#endif // CONFIG_H\n")
outfile.close()
print("Done.")
